language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: edge
    - os: osx
      osx_image: xcode7.2


deploy:
  provider: pages
  local_dir: ${TRAVIS_BUILD_DIR}/docs/build/html
  skip_cleanup: true
  repo: qmlcode/qmlcode.github.io
  target_branch: master
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  on:
    branch: master
    condition: ${TRAVIS_PYTHON_VERSION} = "2.7"

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update -qq

install:
 - |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

    brew install gcc
    pip install numpy
    pip install scipy
    pip install ase
    python setup.py build
    python setup.py install


  else
     sudo apt-get install -qq gcc gfortran libblas-dev liblapack-dev
     sudo apt-get install -qq gcc-4.8 gfortran-4.8

     if [ ${TRAVIS_PYTHON_VERSION:0:1} = 3 ]; then
       sudo apt-get install python3-numpy
       pip3 install scipy
       pip3 install ase
       python3 setup.py build
       python3 setup.py install
       pip3 install sphinx
       pip3 install sphinx-rtd-theme
       cd ${TRAVIS_BUILD_DIR}/docs
       make html
      elif [ ${TRAVIS_PYTHON_VERSION} = "2.7" ]; then
       sudo apt-get install python-numpy
       pip2 install scipy
       pip2 install ase
       python2 setup.py build
       python2 setup.py install
       pip2 install sphinx
       pip2 install sphinx-rtd-theme
       cd ${TRAVIS_BUILD_DIR}/docs
       make html
      else
        echo "ERROR: Unknown Python version."
    fi
  fi

before_script:
 - cd ${TRAVIS_BUILD_DIR}/tests/

script:
 - nosetests -v

notifications:
  email: false
